openapi: 3.0.0
info:
  title: Student's Grades API
  version: 2.0.0
paths:
  /get/student/grades/{id}:
    get:
      summary: Получение данных студента по ID
      parameters:
        - name: id
          in: path
          description: ID студента
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Grade'
        '404':
          description: Студент не найден
  /get/average_grades/{groupId}:
    get:
      summary: Получение средних оценок каждого ученика в указанном классе
      parameters:
        - name: groupId
          in: path
          description: ID класса
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentDTO'
        '404':
          description: Ученики не найдены
  /add/student:
    post:
      summary: Добавление студента
      parameters:
        - name: lastName
          in: query
          description: Фамилия студента
          required: true
          schema:
            type: string
        - name: firstName
          in: query
          description: Имя студента
          required: true
          schema:
            type: string
        - name: age
          in: query
          description: Возраст студента
          required: true
          schema:
            type: integer
        - name: groupId
          in: query
          description: ID класса студента
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
  /delete/student/{id}:
    delete:
      summary: Удаление студента по ID
      parameters:
        - name: id
          in: path
          description: ID студента
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Студент не найден
  /update/grade/{studentId}/{subject}:
    put:
      summary: Редактирование оценки студента по определенному предмету
      parameters:
        - name: studentId
          in: path
          description: ID студента
          required: true
          schema:
            type: integer
        - name: subject
          in: path
          description: Предмет
          required: true
          schema:
            type: string
        - name: newGrade
          in: query
          description: Новая оценка
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Некорректный запрос
        '404':
          description: Студент не найден
components:
  schemas:
    Grade:
      type: object
      properties:
        id:
          type: integer
        student:
          $ref: '#/components/schemas/Student'
        physics:
          type: integer
        mathematics:
          type: integer
        rus:
          type: integer
        literature:
          type: integer
        geometry:
          type: integer
        informatics:
          type: integer
    Student:
      type: object
      properties:
        id:
          type: integer
        family:
          type: string
        name:
          type: string
        age:
          type: integer
        groupId:
          type: integer
    StudentDTO:
      type: object
      properties:
        family:
          type: string
        name:
          type: string
        age:
          type: integer
        groupId:
          type: integer
        averageGrade:
          type: number
servers:
  - description: ЛокалХост
    url: http://localhost:8080/